development:
  adapter: mysql2
  database: rackspace_dev
  encoding: utf8
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  database: rackspace_test
  encoding: utf8
  host: localhost
  username: root
  password: root

production:
  adapter: mysql2
  database: rackspace_prod
  encoding: utf8
  host: localhost
  username: root
  password: root






