class AddFoodCategoriesRows < ActiveRecord::Migration
  def self.up
    FoodCategory.create(:id => 1, :name => 'African')
    FoodCategory.create(:id => 2, :name => 'American')
    FoodCategory.create(:id => 3, :name => 'Argentinian')
    FoodCategory.create(:id => 4, :name => 'Asian')
    FoodCategory.create(:id => 5, :name => 'Australian')
    FoodCategory.create(:id => 6, :name => 'BBQ')
    FoodCategory.create(:id => 7, :name => 'Bakery')
    FoodCategory.create(:id => 8, :name => 'Brazilian')
    FoodCategory.create(:id => 9, :name => 'Breakfast')
    FoodCategory.create(:id => 10, :name => 'Cajun/Creole')
    FoodCategory.create(:id => 11, :name => 'Caribbean')
    FoodCategory.create(:id => 12, :name => 'Chinese')
    FoodCategory.create(:id => 13, :name => 'Coffee/Tea')
    FoodCategory.create(:id => 14, :name => 'Cuban')
    FoodCategory.create(:id => 15, :name => 'Delicatessen') 
    FoodCategory.create(:id => 16, :name => 'Dessert')
    FoodCategory.create(:id => 17, :name => 'Diner')
    FoodCategory.create(:id => 18, :name => 'Eastern European')
    FoodCategory.create(:id => 19, :name => 'Ethiopian')
    FoodCategory.create(:id => 20, :name => 'Falafel')
    FoodCategory.create(:id => 21, :name => 'Fast Food')
    FoodCategory.create(:id => 22, :name => 'Food Truck')
    FoodCategory.create(:id => 23, :name => 'French')
    FoodCategory.create(:id => 24, :name => 'German')
    FoodCategory.create(:id => 25, :name => 'Gluten-free')
    FoodCategory.create(:id => 26, :name => 'Greek')
    FoodCategory.create(:id => 27, :name => 'Hot Dogs')
    FoodCategory.create(:id => 28, :name => 'Ice Cream')
    FoodCategory.create(:id => 29, :name => 'Indian')
    FoodCategory.create(:id => 30, :name => 'Italian')
    FoodCategory.create(:id => 31, :name => 'Korean')
    FoodCategory.create(:id => 32, :name => 'Latin American')
    FoodCategory.create(:id => 33, :name => 'Mediterranean')
    FoodCategory.create(:id => 34, :name => 'Middle Eastern')
    FoodCategory.create(:id => 35, :name => 'Moroccan')
    FoodCategory.create(:id => 36, :name => 'Pizza')
    FoodCategory.create(:id => 37, :name => 'Salads')
    FoodCategory.create(:id => 38, :name => 'Sandwiches')
    FoodCategory.create(:id => 39, :name => 'Scandinavian')
    FoodCategory.create(:id => 40, :name => 'Seafood')
    FoodCategory.create(:id => 41, :name => 'South American')
    FoodCategory.create(:id => 42, :name => 'Southern/Soul Food')
    FoodCategory.create(:id => 43, :name => 'Spanish')
    FoodCategory.create(:id => 44, :name => 'Steakhouse')
    FoodCategory.create(:id => 45, :name => 'Sushi')
    FoodCategory.create(:id => 46, :name => 'Swiss')
    FoodCategory.create(:id => 47, :name => 'Tacos')
    FoodCategory.create(:id => 48, :name => 'Tapas')
    FoodCategory.create(:id => 49, :name => 'Thai')
    FoodCategory.create(:id => 50, :name => 'Vegetarian/Vegan')
    FoodCategory.create(:id => 51, :name => 'Vietnamese')
    FoodCategory.create(:id => 52, :name => 'Wine')
    FoodCategory.create(:id => 53, :name => 'Wings')
  end

  def self.down
  end
end
